### ISSUE TITLE
Replace all octokit uses for suggested changes

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/reviewing-a-pull-request#72]
The `pullRequests.createComment` octokit method is now a [Learning Lab action](https://github.com/github/learning-lab/pull/1020). This course contains some of its use that should be replaced.

**Comment by crichID** [comment]
Example of one instance is [here](https://github.com/githubtraining/reviewing-a-pull-request/blob/e3433782ea398cdb2cbeb83e3dc204f2cd55ef33/config.yml#L156-L185). 

When we make this change, we'll also want to change the response to reflect UI changes:

<img width="443" alt="Screen Shot 2019-06-28 at 1 40 57 PM" src="https://user-images.githubusercontent.com/1221423/60370082-7b156300-99aa-11e9-864b-d317b7003cf4.png">

**Comment by hectorsector** [comment]
Looks like the was taken care of in https://github.com/githubtraining/reviewing-a-pull-request/pull/73 and https://github.com/githubtraining/reviewing-a-pull-request/pull/89 🎉 

Thanks @JasonEtco and @harshmadhani
