### ISSUE TITLE
In fixing a pulling request step, change Apply Suggestion to Commit suggestion

### ISSUE THREAD

**Issue by harshmadhani** [githubtraining/reviewing-a-pull-request#88]
## Bug Report

**Current behavior**
The issue occurs in the fourth step of reviewing a pull request. While applying the suggestion to the pull request, it suggests to click on "Apply Suggestion", but I could only see "Commit Suggestion". Attached below image.

![reviewing-changes](https://user-images.githubusercontent.com/1668599/84816422-e29c4680-b031-11ea-9153-6bba8f8a19c8.png)

**Reproduction**
Steps to reproduce the behavior in the course:
1. Go to 'https://github.com/<your-user-name>/reviewing-a-pull-request/pull/4'
2. Update the description of the pull request created
3. Scroll down to 'Activity : Apply the suggestion'

**Expected behavior**
We need to make change in the text from "Apply Suggestion" to "Commit Suggestion"

**Possible solution**
We can make change in config.yml file of the repo

**Comment by davenowell** [comment]
@harshmadhani  Thank you for reporting this.

**Comment by harshmadhani** [comment]
@davenowell I have raised a PR #89 for it. Can you please review it or suggest any changes?
